### ISSUE TITLE
Documentation v1.5

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1916]
This page keeps track of ALL documentation efforts in V1.5.

- [ ] Broken documentation link + add (?) everywhere: https://github.com/codalab/codalab-competitions/issues/1971, https://github.com/codalab/codalab-competitions/issues/1797
- [x] Oudated doc pages https://github.com/codalab/codalab-competitions/issues/1964
- [x] Dev doc issues: https://github.com/codalab/codalab-competitions/issues/1928, https://github.com/codalab/codalab-competitions/issues/1927
- [ ] 
- [ ]

**Comment by madclam** [comment]
Question: to whom are the instructions on https://github.com/codalab/codalab-competitions/blob/develop/README.md directed? Why is this not part of the documentation?

**Comment by madclam** [comment]
Document GPU compute workers.

**Comment by ckcollab** [comment]
Fixed link for Worker Queues

**Comment by ckcollab** [comment]
Pushed to azure staging, added the label so we know!
