### ISSUE TITLE
AutoDL Todo:

### ISSUE THREAD

**Issue by Tthomas63** [codalab/codalab-competitions#2435]
- [x] When we click on the results tab: we get to the "dataset5" tab, not to "all datasets".
- [x] Number of participants: we should only count people having made at least one submission.
- [x] Number of submissions: this is hyper-inflated because when we have 1 master track with 5 subtracks, for each submission, the counter is incremented by 6!
- [x] When one tries to click on "Re-run" submission, it will only re-run the submission for current phase (e.g. parent phase), but not for all sub-phases. 
- [x] There is no email verification at sign up time, this needs to be turned on.
- [x] On first submission upload as a regular participant we get a message about registration needing approval even if registration is off

New Message: 
![image](https://user-images.githubusercontent.com/28552312/46690852-3fd2ca00-cbb8-11e8-93ab-81b428c130e7.png)

**Comment by madclam** [comment]
[-] The cancel button does not seem to have any effect while in the “Submitting” mode.
[-] When canceling a job, the page does not show that the job is canceled unless we refresh.

**Comment by madclam** [comment]
![image](https://user-images.githubusercontent.com/7594063/46703145-bed8fa00-cbda-11e8-8bc4-3b510f46e1bb.png)

**Comment by zhengying-liu** [comment]
Also when encountering above issue, one cannot cancel the submission, e.g. 2 and 4 in the picture. This means that when clicking on 'Cancel', nothing happens...

**Comment by Tthomas63** [comment]
Currently Codalab has only supported filenames up to 36 characters (100 total with the storage path included). I have pushed a fix to give a better error message specifically about file-name length and preventing the upload from happening in the first place.

![image 2](https://user-images.githubusercontent.com/28552312/46825740-32991500-cd49-11e8-804d-3579b58904c8.png)

**Comment by Tthomas63** [comment]
I believe the cancel behavior is much better now, and should have been addressed. If this is still an issue we can re-open it and take another look.
