### ISSUE TITLE
[Merged] AutoDL/v1.8 wish list and issues

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2609]
This issue recaps wishes made for AutoDL that have found work arounds and have lesser priority.
(Lukasz will test)

UI FIXES (Tyler)
- [x]  Add server time on web page AND Add UTC after "Competition Ends:" date and [in the schedule](https://github.com/codalab/codalab-competitions/issues/2605)
- [x]  [UI change suggested by Andre](https://github.com/codalab/codalab-competitions/issues/2601)
- [ ] Results are not showing properly in the admin submission panel.

BUGS (many emails were sent about it with the links to the issues on the forum):
- [ ]  Error in computing total execution time (shows more time used than the sum of children)
- [ ]  Weird "Submission Failed" (submission OK but denoted failed)

QUEUE PROBLEMS (Eric)
Implement diagnosis tools for queueing - Fix the FIFO - elastic cloud
- [ ]  [Improve admin tools](https://github.com/codalab/codalab-competitions/issues/2585). We should monitor whether there are some jobs stuck waiting for abnormal times. Statistics for queue monitoring see also [elastic cloud](https://sites.google.com/a/chalearn.org/platform/hardware/elastic-cloud).
- [x]  [Check parent scoring program never stuck in submitting mode.](https://github.com/codalab/codalab-competitions/issues/2580)
- [ ]  GET CANCEL TO WORK: [Check cancel behavior works properly](https://github.com/codalab/codalab-competitions/issues/2595) Also: When we are in the admin "Submissions" panel and click on a "cancel" button, we are redirected to the main competition page; no acknowledgement cancel was done and we leave the "Submissions" panel page. Also [Submissions cannot be dowloaded if canceled or failed.](https://github.com/codalab/codalab-competitions/issues/2611)
- [x] [Erratic compute time](https://github.com/codalab/codalab-competitions/issues/2608) Difference between compute time and duration; runaway time then a program fails. See also [this bug report](https://github.com/codalab/codalab-competitions/issues/2615) and the fact that [jobs of workers that died never get marked as cancelled or failed](https://github.com/codalab/codalab-competitions/issues/2617).

TWO PHASE PROBLEM
Two parent phases - Having a final phase and migrating automatically:
- [ ]  Button for starting auto-migration (priority not possible for v1.8)
- [ ]  Get auto-migration to work properly for multiple-parent-phase competitions when we have children phases.
- (AutoDL Auto-Migration Competition Demo: #2626)

LATER
- [ ]  [Add new pages in editor](https://github.com/codalab/codalab-competitions/issues/2567)
- [ ]  [Missing parent scoring program execution](https://github.com/codalab/codalab-competitions/issues/2612)
- [ ]  Add warning when people make a submission in a [sub-phase.](https://github.com/codalab/codalab-competitions/issues/2559)
- [ ]  Check that "If submission beats old score, put submission on leaderboard" works properly (for the moment we show the last submission).
- [ ]  Verify that [a competitions has the correct boxes checked](https://github.com/codalab/codalab-competitions/issues/2588) before launching it. Document this behavior with parent and children phases and look at forward compatibility with v2.
- [ ]  [Prefix error messages with name of program it is coming from](https://github.com/codalab/codalab-competitions/issues/2590)
- [ ]  [Improve refresh](https://github.com/codalab/codalab-competitions/issues/2616)

**Comment by Didayolo** [comment]
Issue with 50 phases/datasets: #2703

**Comment by Didayolo** [comment]
Issues:
 * [ ] Dump in autodl cannot be reloaded #2825
 * [ ] Error: [Errno 104] Connection reset by peer #2774
 * [ ] Downloading processes block the website #2752
 * [ ] Weird compute time #2674
 * [ ] Uploading size limit: 2GB #2625

**Comment by Didayolo** [comment]
What about this version 1.8? It is used and maintain somewhere?

**Comment by Didayolo** [comment]
Deprecated
