### ISSUE TITLE
[Merged] Codalab Python3 issues

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2959]
Codalab Python3 is currently deployed here: ~~[codalab.sunai.uoc.edu](https://codalab.sunai.uoc.edu/)~~ (update needed) and [codalab.lisn.fr](https://codalab.lisn.fr/)
The issues encountered in the Python3 LRI / Barcelona instance [B: default] or LISN instance [L]:

Important issues:
* [x] Impossible to create a worker queue #2962 [B]
* [x] Impossible to create a worker queue [L]: not tested yet. **[P1]**
* [x] Can't delete competitions #2958 [B]
* [x] Can't delete competitions [L]
* [x] No detailed results page #2887 **[Loic]** [B, L]
* [x] Cannot create new user #2885 [B, L] OK now
* [x] ~Cannot submit, because says migrating #2879 [B]~ _Barcelona server not up to date_
* [x] Cannot submit, because says migrating [L]
* [x] Bug in saving edits #2878 [B] [L]
* [x] **Error message in results tab** #3001 [L]
* [x] #3018 [L]

Secondary, GUI issues:
* [x] #3002 [B?, L]
* [x] #2877 [B, Button deactivated in L]
* [x] #2862 [B, L]
* [x] #2860 [B, L]
* [x] #3027 
* [x] Competition's submission drop down menu selector not working in py3 version [B, L]
       #2998 
       #2999 
* [ ] #2851 [B, L]

Testing:

* [x] #2856 **[P1]** [L]
* [x] #2858 [B, L]
* [x] Unclear error messages when user each storage limit #2853 [B, L]
* [x] "Delete all submissions except latest and or best" not working #2853 [B, L]
* [x] **Important test: running submissions on external workers [B, L]**
* [x] [Automatic tests are not passing anymore](https://app.circleci.com/pipelines/github/codalab/codalab-competitions?branch=lri-py3-storage)

TODOs:

* [x]  Put a new message warning for D-day: [https://competitions.codalab.org/](https://competitions.codalab.org/)
* [X] ~~Redirect https://competitions.codalab.org/ to https://codalab.lisn.fr/ when everything is working~~
* [x] De-activate the possibility to create new competitions on the old v15 instance. A clear message should appears explaining WHY it does not work and WHERE is the new instance

After the upgrade:
* [x] #2837

_Remark: a checked box means that the issue is solved now._

**Comment by Didayolo** [comment]
Now we can't create new user accounts. However it seems that there is no email confirmation needed.

**Comment by Didayolo** [comment]
**It's still impossible to delete a competition #2958**

**Comment by Didayolo** [comment]
"Impossible to create a worker queue" solved!

**Comment by Didayolo** [comment]
(1) Email notifications are not working
@Adrien: Make sure you know how to set up the mail server, you might need Laurent’s help.

(2) Competition dump with URI keys failed
https://codalab.sunai.uoc.edu/competitions/793/dumps/

(3) When creating a new phase (phase 3) in 
https://codalab.sunai.uoc.edu/competitions/794
the menus showed all data bundles;
This is a potential security breach.
The bug shows only when a new phase is created.

There are many other issues, but for now I marked them as P2.
Best regards,

Isabelle



Account creation:
py3tester
No email verification (P1)

Updated profile
checked: Email on submission finished successfully
No email receive  (P2)

Follow 
https://github.com/madclam/m1ai2021
Upload competition Iris
(no progress bar) => say "be patient"; show prominent result button.

Competition uploaded
https://codalab.sunai.uoc.edu/competitions/793

Made all 3 sample submissions
Checked editing submission description works

Editor
Download original YAML
Made minor edits (logo, teams)


SUBMISSIONS (organizer) TAB:
All submissions are showing, regardless of phase (confusing)
Restricting to a given phase does not work (P2)
Results do not show in panel (P2)
Manual migration to new phase: works.
Delete submission works
Mark as failed works
BUT: A failed submission can be shown on the leaderboard
https://codalab.sunai.uoc.edu/competitions/794#results
Impossible to unmark it as failed
Output log ingestions ans scoring get downloaded, others get displayed
Error log ingestion is empty
Detailed results is empty
Private output is empty


Detailed results do not show (P2):
https://codalab.sunai.uoc.edu/my/competition/submission/13482/detailed_results/
It DOES work on the original server
https://competitions.codalab.org/competitions/27804#results

Participant panel:
Email sent, not received (P2)

Competition dump with URI keys
Failed (P1)
works in https://competitions.codalab.org/competitions/27804/dumps/
Competition dump wo URI keys
Success, 
https://codalab.sunai.uoc.edu/competitions/794
but YAML/editor options changed (P2)
Show datasets from yaml, re-enabled
Allow teams, disabled
Enable forum, disabled
Execution time limit changed
If submission beats old score, changed

Secret Url works

Changing phase dates work

Creating new phase
Works
Why does the menu show all data bundles (P1)
Could not reproduce in https://competitions.codalab.org/competitions/edit_competition/27804 (no new phase button)

Widgets:
https://codalab.sunai.uoc.edu/competitions/794/widgets/
don't work (P2)
Fist one works in
https://competitions.codalab.org/competitions/27804/widgets/

**Comment by loicsarrazin** [comment]
Regarding Issue #2856 , it seems that the bug is not reproductible on the https://codalab.lisn.fr/ deployment, as well as locally. Could it be linked to the server being quite busy?  
I also found [this other bug report](https://groups.google.com/g/codalab-competitions/c/5bi3mxL8eWA) under py2, and it seems any modification made to the competition would not be saved correctly if any phase is being migrated.  
  
With your approbation @Didayolo I suggest we close this issue, and create a new task that verifies that a migration is actually occuring on a phase of this competition when the "Failed, competition phase is being migrated, please try again in a few minutes" appears.

**Comment by Didayolo** [comment]
Bug in saving edits #2878 : still the case on [codalab.lisn.fr](codalab.lisn.fr)

**Comment by Didayolo** [comment]
The automatic tests are not passing anymore:
 [https://app.circleci.com/pipelines/github/codalab/codalab-competitions?branch=lri-py3-storage](https://app.circleci.com/pipelines/github/codalab/codalab-competitions?branch=lri-py3-storage)

**Comment by loicsarrazin** [comment]
Checked this issue : https://github.com/codalab/codalab-competitions/issues/2887. The fix is indeed present on codalab.lisn.fr. Leaving the ticket opened since the bug is still on the python 2 version. To close when the switch to 1.5 is complete.

**Comment by loicsarrazin** [comment]
Check the " Can't delete competitions [L]" issue, as after verification it is not a problem anymore from the user interface of https://github.com/codalab/codalab-competitions/issues/codalab.lisn.fr.

**Comment by loicsarrazin** [comment]
Moving [CodalabPy3] Impossible to make submissions after a deadline extension #2856 to TODO as I am unable to reproduce the bug on codalab.sunai.uoc.edu/ after doing the following actions :  
- Create competition
- Edit End of competition date to a date in the (very near) future
- Wait until the end date and time is passed
- Edit the End of competition date to a date in the future
- Submit submission.
I have not encountered the problem.

**Comment by loicsarrazin** [comment]
Checking "Impossible to create a worker queue [L]: not tested yet. [P1]".  Queue successfully created on codalab.lisn.upsaclay.fr/

**Comment by loicsarrazin** [comment]
Merging the two issues related to LRI server: bug in saving edits #2878 as the bug occurs on both versions

**Comment by loicsarrazin** [comment]
Updated the issues associated to the Submissions view phase selector that won't work under some precise circumstances, and that is kind of buggy at the moment.

**Comment by Didayolo** [comment]
> Moving [CodalabPy3] Impossible to make submissions after a deadline extension #2856 to TODO as I am unable to reproduce the bug on codalab.sunai.uoc.edu/ after doing the following actions :
> 
>     * Create competition
> 
>     * Edit End of competition date to a date in the (very near) future
> 
>     * Wait until the end date and time is passed
> 
>     * Edit the End of competition date to a date in the future
> 
>     * Submit submission.
>       I have not encountered the problem.

I think the best way to reproduce this is to change the end date of a competition to a past date directly in the `competition.yaml` file, and then upload the bundle. Once the competition is up, go to edit menu and extend deadline, then submit.
I tried and everything worked well.

**Comment by Didayolo** [comment]
I've seen some instabilities in LISN server.
At some point the server was down and I have to restart it with `docker-compose up -d`.

Also, recently, the health simple status page was not working, and then came back to life:
#3016
